// lib/product-audit/product-audit.constants.ts
// =============================================================================
// AUDIT PRODUIT — Codes d'actions normalisés (AuditLog.action)
// =============================================================================

export const PRODUCT_AUDIT_ACTIONS = {
  CREATED: "PRODUCT_CREATED",
  UPDATED: "PRODUCT_UPDATED",
  DELETED: "PRODUCT_DELETED",
  RESTORED: "PRODUCT_RESTORED",
  PUBLISHED: "PRODUCT_PUBLISHED",
  UNPUBLISHED: "PRODUCT_UNPUBLISHED",
  ARCHIVED: "PRODUCT_ARCHIVED",
  SCHEDULED: "PRODUCT_SCHEDULED",
  APPROVAL_REQUESTED: "PRODUCT_APPROVAL_REQUESTED",
  STATUS_CHANGED: "PRODUCT_STATUS_CHANGED",
  PRICE_CHANGED: "PRODUCT_PRICE_CHANGED",
  STOCK_ADJUSTED: "PRODUCT_STOCK_ADJUSTED",
  STOCK_RESERVED: "PRODUCT_STOCK_RESERVED",
  STOCK_RELEASED: "PRODUCT_STOCK_RELEASED",
  VARIANT_CREATED: "PRODUCT_VARIANT_CREATED",
  VARIANT_DELETED: "PRODUCT_VARIANT_DELETED",
  CATEGORY_CHANGED: "PRODUCT_CATEGORY_CHANGED",
  CATALOG_CHANGED: "PRODUCT_CATALOG_CHANGED",
} as const;

export type ProductAuditAction =
  (typeof PRODUCT_AUDIT_ACTIONS)[keyof typeof PRODUCT_AUDIT_ACTIONS];
